source('loadData.R')
trn <- loadData('songListTrainSet')
vld <- loadData('songListValidationSet')
tst <- loadData('songListTestSet')
source('NMF.R')
out <- ratingProbsFit(trn, 5, 'NMF', FALSE, list(nthread = 4, index1 = TRUE))