source('loadData.R')
trn <- loadData('songListTrainSet')
vld <- loadData('songListValidationSet')
tst <- loadData('songListTestSet')
source('crossValidate.R')
x <- crossValidate(trn, vld, tst, 5, "NMF", FALSE, FALSE)